# Generated by Django 4.2.1 on 2023-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_about_us_company_name_alter_about_us_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='About_us_image',
            field=models.ImageField(null=True, upload_to='carousel_images/'),
        ),
    ]
