# Generated by Django 4.1.6 on 2023-05-16 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_about_us_about_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_challenges',
            field=models.TextField(max_length=100),
        ),
    ]
