# Generated by Django 4.1.6 on 2023-05-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_published_by_alter_project_project_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
