# Generated by Django 4.1.6 on 2023-05-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Image',
            new_name='Publisher_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
