# Generated by Django 4.1.6 on 2023-05-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_blog_publisher_image_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feature'),
        ),
    ]
