# Generated by Django 4.1.6 on 2023-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_package_features_package_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.ManyToManyField(to='app.feature'),
        ),
    ]
