# Generated by Django 4.1.6 on 2023-05-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_package_features_package_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='comments',
            field=models.TextField(max_length=1000),
        ),
    ]
