# Generated by Django 4.1.6 on 2023-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_appointment_id_appointment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
