# Generated by Django 4.2.1 on 2023-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
    ]
