# Generated by Django 4.1.6 on 2023-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_service_image_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(null=True, upload_to='carousel_images'),
        ),
    ]
