# Generated by Django 4.2.1 on 2023-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_about_us_image_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='projects/carousel/'),
        ),
    ]
