# Generated by Django 4.2.1 on 2023-05-21 18:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_about_us_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='form_submissions/')),
            ],
        ),
        migrations.AlterField(
            model_name='about_us',
            name='logo',
            field=app.models.SVGField(null=True, upload_to='logo'),
        ),
    ]
