# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_formsubmission_alter_about_us_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='excel_file',
            field=models.FileField(upload_to='projects/form_submissions/'),
        ),
    ]
