# Generated by Django 4.2.1 on 2023-05-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_formsubmission_excel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_challenges',
            new_name='project_Description',
        ),
    ]
