# Generated by Django 4.2.1 on 2023-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_project_challenges_project_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='excel_file',
            field=models.FileField(upload_to='form_submissions/'),
        ),
    ]
