# Generated by Django 4.2.1 on 2023-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_formsubmission_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('morning', models.BooleanField(default=False)),
                ('noon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('customTimeSlot', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='TFN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='bsb_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='emergency_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='passportnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='availabilities',
            field=models.ManyToManyField(to='app.availability'),
        ),
    ]
