# Generated by Django 4.2.1 on 2023-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_availability_remove_formsubmission_excel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='covidVaccination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='policeChecksnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='wwccnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
