# Generated by Django 4.2.1 on 2023-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_formsubmission_covidvaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='policeChecks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='wwcc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
