# Generated by Django 4.2.1 on 2023-05-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_about_us_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='name',
        ),
    ]
