# Generated by Django 4.2.1 on 2023-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_testimony_image_remove_testimony_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
